name: representation-learning
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=20.0.2=py38_3
  - python=3.8.1=h0371630_1
  - pytorch=1.7.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.1=py38_cu101
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==8.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - dataclasses==0.6
    - decorator==5.0.9
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - envyaml==1.8.210417
    - fsspec==2021.6.1
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.31.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.0
    - hydra-core==1.1.0
    - idna==2.10
    - importlib-resources==5.2.0
    - ipykernel==5.1.4
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonargparse==3.16.0
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.1.3
    - mistune==0.8.4
    - multidict==5.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.0.3
    - oauthlib==3.1.1
    - omegaconf==2.1.0
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.0.1
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plotly==4.8.1
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyro-api==0.1.2
    - pyro-ppl==1.3.1
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-dotenv==0.18.0
    - pytorch-lightning==1.3.8
    - pytorch-revgrad==0.1.1
    - pytz==2021.1
    - pyyaml==5.3
    - pyzmq==22.1.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.7.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.10.0
    - send2trash==1.5.0
    - sentry-sdk==1.1.0
    - shortuuid==1.0.1
    - sklearn==0.0
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.10.1
    - testpath==0.5.0
    - torchaudio==0.7.0
    - torchmetrics==0.4.1
    - tornado==6.1
    - tqdm==4.42.1
    - traitlets==5.0.5
    - urllib3==1.26.5
    - wandb==0.11.0
    - watchdog==2.1.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - yarl==1.6.3
    - zipp==3.5.0